config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :authorized_associates

      resources :saved_appointments

      resources :services

      resources :dog_profiles

      resources :dog_owner_profiles

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "dog_owner_profiles#index"
  resources :authorized_associates
  resources :saved_appointments
  resources :services
  resources :dog_profiles
  resources :dog_owner_profiles
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/service.rb
class Service < ApplicationRecord
  # Direct associations

  belongs_to :saved_appointment,
             optional: true,
             counter_cache: true

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    shampoo
  end
end

app/controllers/api/v1/services_controller.rb
class Api::V1::ServicesController < Api::V1::GraphitiController
  def index
    services = ServiceResource.all(params)
    respond_with(services)
  end

  def show
    service = ServiceResource.find(params)
    respond_with(service)
  end

  def create
    service = ServiceResource.build(params)

    if service.save
      render jsonapi: service, status: :created
    else
      render jsonapi_errors: service
    end
  end

  def update
    service = ServiceResource.find(params)

    if service.update_attributes
      render jsonapi: service
    else
      render jsonapi_errors: service
    end
  end

  def destroy
    service = ServiceResource.find(params)

    if service.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: service
    end
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: %i[show edit update destroy]

  def index
    @q = Service.ransack(params[:q])
    @services = @q.result(distinct: true).includes(:saved_appointment).page(params[:page]).per(10)
  end

  def show; end

  def new
    @service = Service.new
  end

  def edit; end

  def create
    @service = Service.new(service_params)

    if @service.save
      message = "Service was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @service, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @service.update(service_params)
      redirect_to @service, notice: "Service was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @service.destroy
    message = "Service was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to services_url, notice: message
    end
  end

  private

  def set_service
    @service = Service.find(params[:id])
  end

  def service_params
    params.require(:service).permit(:shampoo, :pest_treatment, :condition,
                                    :nail_trim, :pad_shaving, :ear_cleaning, :teeth_brushing, :gland_cleaning, :hair_cut, :hair_trim, :brushing, :saved_appointment_id)
  end
end

app/views/services/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Service #<%= service.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Shampoo</dt>
      <dd><%= service.shampoo %></dd>

      <dt>Pest treatment</dt>
      <dd><%= service.pest_treatment %></dd>

      <dt>Condition</dt>
      <dd><%= service.condition %></dd>

      <dt>Nail trim</dt>
      <dd><%= service.nail_trim %></dd>

      <dt>Pad shaving</dt>
      <dd><%= service.pad_shaving %></dd>

      <dt>Ear cleaning</dt>
      <dd><%= service.ear_cleaning %></dd>

      <dt>Teeth brushing</dt>
      <dd><%= service.teeth_brushing %></dd>

      <dt>Gland cleaning</dt>
      <dd><%= service.gland_cleaning %></dd>

      <dt>Hair cut</dt>
      <dd><%= service.hair_cut %></dd>

      <dt>Hair trim</dt>
      <dd><%= service.hair_trim %></dd>

      <dt>Brushing</dt>
      <dd><%= service.brushing %></dd>

      <dt>Saved appointment</dt>
      <dd>
        <% if @service.saved_appointment.present? %>
          <%= link_to service.saved_appointment, service.saved_appointment %>
        <% end %>
      </dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back service, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_service_url(service), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to service, method: :delete, data: { confirm: "Do you really want to delete this service?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(service.updated_at) %> ago
  </div>
</div>

app/views/services/_form.html.erb
<% was_validated = service.errors.any? %>

<%= form_with(model: service, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% shampoo_class = "form-control" %>
    <% shampoo_was_invalid = service.errors.include?(:shampoo) %>

    <% if was_validated %>
      <% if shampoo_was_invalid %>
        <% shampoo_class << " is-invalid" %>
      <% else %>
        <% shampoo_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :shampoo %>
    <%= f.text_field :shampoo, class: shampoo_class, placeholder: "Enter shampoo" %>
    <% if shampoo_was_invalid %>
      <% service.errors.full_messages_for(:shampoo).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% pest_treatment_class = "form-control" %>
    <% pest_treatment_was_invalid = service.errors.include?(:pest_treatment) %>

    <% if was_validated %>
      <% if pest_treatment_was_invalid %>
        <% pest_treatment_class << " is-invalid" %>
      <% else %>
        <% pest_treatment_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :pest_treatment %>
    <%= f.text_field :pest_treatment, class: pest_treatment_class, placeholder: "Enter pest treatment" %>
    <% if pest_treatment_was_invalid %>
      <% service.errors.full_messages_for(:pest_treatment).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% condition_class = "form-control" %>
    <% condition_was_invalid = service.errors.include?(:condition) %>

    <% if was_validated %>
      <% if condition_was_invalid %>
        <% condition_class << " is-invalid" %>
      <% else %>
        <% condition_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :condition %>
    <%= f.text_field :condition, class: condition_class, placeholder: "Enter condition" %>
    <% if condition_was_invalid %>
      <% service.errors.full_messages_for(:condition).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% nail_trim_class = "form-control" %>
    <% nail_trim_was_invalid = service.errors.include?(:nail_trim) %>

    <% if was_validated %>
      <% if nail_trim_was_invalid %>
        <% nail_trim_class << " is-invalid" %>
      <% else %>
        <% nail_trim_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :nail_trim %>
    <%= f.text_field :nail_trim, class: nail_trim_class, placeholder: "Enter nail trim" %>
    <% if nail_trim_was_invalid %>
      <% service.errors.full_messages_for(:nail_trim).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% pad_shaving_class = "form-control" %>
    <% pad_shaving_was_invalid = service.errors.include?(:pad_shaving) %>

    <% if was_validated %>
      <% if pad_shaving_was_invalid %>
        <% pad_shaving_class << " is-invalid" %>
      <% else %>
        <% pad_shaving_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :pad_shaving %>
    <%= f.text_field :pad_shaving, class: pad_shaving_class, placeholder: "Enter pad shaving" %>
    <% if pad_shaving_was_invalid %>
      <% service.errors.full_messages_for(:pad_shaving).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% ear_cleaning_class = "form-control" %>
    <% ear_cleaning_was_invalid = service.errors.include?(:ear_cleaning) %>

    <% if was_validated %>
      <% if ear_cleaning_was_invalid %>
        <% ear_cleaning_class << " is-invalid" %>
      <% else %>
        <% ear_cleaning_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :ear_cleaning %>
    <%= f.text_field :ear_cleaning, class: ear_cleaning_class, placeholder: "Enter ear cleaning" %>
    <% if ear_cleaning_was_invalid %>
      <% service.errors.full_messages_for(:ear_cleaning).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% teeth_brushing_class = "form-control" %>
    <% teeth_brushing_was_invalid = service.errors.include?(:teeth_brushing) %>

    <% if was_validated %>
      <% if teeth_brushing_was_invalid %>
        <% teeth_brushing_class << " is-invalid" %>
      <% else %>
        <% teeth_brushing_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :teeth_brushing %>
    <%= f.text_field :teeth_brushing, class: teeth_brushing_class, placeholder: "Enter teeth brushing" %>
    <% if teeth_brushing_was_invalid %>
      <% service.errors.full_messages_for(:teeth_brushing).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% gland_cleaning_class = "form-control" %>
    <% gland_cleaning_was_invalid = service.errors.include?(:gland_cleaning) %>

    <% if was_validated %>
      <% if gland_cleaning_was_invalid %>
        <% gland_cleaning_class << " is-invalid" %>
      <% else %>
        <% gland_cleaning_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :gland_cleaning %>
    <%= f.text_field :gland_cleaning, class: gland_cleaning_class, placeholder: "Enter gland cleaning" %>
    <% if gland_cleaning_was_invalid %>
      <% service.errors.full_messages_for(:gland_cleaning).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% hair_cut_class = "form-control" %>
    <% hair_cut_was_invalid = service.errors.include?(:hair_cut) %>

    <% if was_validated %>
      <% if hair_cut_was_invalid %>
        <% hair_cut_class << " is-invalid" %>
      <% else %>
        <% hair_cut_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :hair_cut %>
    <%= f.text_field :hair_cut, class: hair_cut_class, placeholder: "Enter hair cut" %>
    <% if hair_cut_was_invalid %>
      <% service.errors.full_messages_for(:hair_cut).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% hair_trim_class = "form-control" %>
    <% hair_trim_was_invalid = service.errors.include?(:hair_trim) %>

    <% if was_validated %>
      <% if hair_trim_was_invalid %>
        <% hair_trim_class << " is-invalid" %>
      <% else %>
        <% hair_trim_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :hair_trim %>
    <%= f.text_field :hair_trim, class: hair_trim_class, placeholder: "Enter hair trim" %>
    <% if hair_trim_was_invalid %>
      <% service.errors.full_messages_for(:hair_trim).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% brushing_class = "form-control" %>
    <% brushing_was_invalid = service.errors.include?(:brushing) %>

    <% if was_validated %>
      <% if brushing_was_invalid %>
        <% brushing_class << " is-invalid" %>
      <% else %>
        <% brushing_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :brushing %>
    <%= f.text_field :brushing, class: brushing_class, placeholder: "Enter brushing" %>
    <% if brushing_was_invalid %>
      <% service.errors.full_messages_for(:brushing).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% saved_appointment_class = "form-control" %>
    <% saved_appointment_was_invalid = service.errors.include?(:saved_appointment) %>

    <% if was_validated %>
      <% if saved_appointment_was_invalid %>
        <% saved_appointment_class << " is-invalid" %>
      <% else %>
        <% saved_appointment_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :saved_appointment_id %>
    <%= f.collection_select :saved_appointment_id, SavedAppointment.all, :id, :to_s, {}, class: "form-control" %>
    <% if saved_appointment_was_invalid %>
      <% service.errors.full_messages_for(:saved_appointment).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/services/_list_item.html.erb
<%= link_to service, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= service %>
    <small class="text-muted">
      <%= time_ago_in_words(service.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/services/_services_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "services_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :shampoo_cont, "Shampoo contains" %>
    <%= f.text_field :shampoo_cont, :class => "form-control", :placeholder => "Shampoo contains" %>
  </div>

  <div class="form-group">
    <%= f.label :brushing_cont, "Brushing contains" %>
    <%= f.text_field :brushing_cont, :class => "form-control", :placeholder => "Brushing contains" %>
  </div>

  <div class="form-group">
    <%= f.label :hair_trim_cont, "Hair trim contains" %>
    <%= f.text_field :hair_trim_cont, :class => "form-control", :placeholder => "Hair trim contains" %>
  </div>

  <div class="form-group">
    <%= f.label :hair_cut_cont, "Hair cut contains" %>
    <%= f.text_field :hair_cut_cont, :class => "form-control", :placeholder => "Hair cut contains" %>
  </div>

  <div class="form-group">
    <%= f.label :gland_cleaning_cont, "Gland cleaning contains" %>
    <%= f.text_field :gland_cleaning_cont, :class => "form-control", :placeholder => "Gland cleaning contains" %>
  </div>

  <div class="form-group">
    <%= f.label :teeth_brushing_cont, "Teeth brushing contains" %>
    <%= f.text_field :teeth_brushing_cont, :class => "form-control", :placeholder => "Teeth brushing contains" %>
  </div>

  <div class="form-group">
    <%= f.label :ear_cleaning_cont, "Ear cleaning contains" %>
    <%= f.text_field :ear_cleaning_cont, :class => "form-control", :placeholder => "Ear cleaning contains" %>
  </div>

  <div class="form-group">
    <%= f.label :pad_shaving_cont, "Pad shaving contains" %>
    <%= f.text_field :pad_shaving_cont, :class => "form-control", :placeholder => "Pad shaving contains" %>
  </div>

  <div class="form-group">
    <%= f.label :nail_trim_cont, "Nail trim contains" %>
    <%= f.text_field :nail_trim_cont, :class => "form-control", :placeholder => "Nail trim contains" %>
  </div>

  <div class="form-group">
    <%= f.label :condition_cont, "Condition contains" %>
    <%= f.text_field :condition_cont, :class => "form-control", :placeholder => "Condition contains" %>
  </div>

  <div class="form-group">
    <%= f.label :pest_treatment_cont, "Pest treatment contains" %>
    <%= f.text_field :pest_treatment_cont, :class => "form-control", :placeholder => "Pest treatment contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>




  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/services" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#services_filters">
  Show filters
</a>

app/views/services/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Service #<%= @service.id %>
      </h2>

      <div class="card-body">
        <%= render "form", service: @service %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/services/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Services

      <%= link_to new_service_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "services/services_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Services

        <%= link_to new_service_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @services, partial: "list_item", as: :service %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @services, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/services/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Service
      </h2>

      <div class="card-body">
        <%= render "form", service: @service %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/services/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @service, partial: "card", as: :service %>
  </div>
</div>