config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :authorized_associates

      resources :saved_appointments

      resources :services

      resources :dog_profiles

      resources :dog_owner_profiles

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "dog_owner_profiles#index"
  resources :authorized_associates
  resources :saved_appointments
  resources :services
  resources :dog_profiles
  resources :dog_owner_profiles
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  include JwtToken
  # Direct associations

  has_many   :dog_owner_profiles,
             dependent: :destroy

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    email
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::GraphitiController
  def index
    users = UserResource.all(params)
    respond_with(users)
  end

  def show
    user = UserResource.find(params)
    respond_with(user)
  end

  def create
    user = UserResource.build(params)

    if user.save
      render jsonapi: user, status: :created
    else
      render jsonapi_errors: user
    end
  end

  def update
    user = UserResource.find(params)

    if user.update_attributes
      render jsonapi: user
    else
      render jsonapi_errors: user
    end
  end

  def destroy
    user = UserResource.find(params)

    if user.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: user
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @users = User.page(params[:page]).per(10)
  end

  def show
    @dog_owner_profile = DogOwnerProfile.new
  end

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: "User was successfully created."
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "User was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: "User was successfully destroyed."
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.fetch(:user, {})
  end
end

app/views/users/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    User #<%= user.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back user, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_user_url(user), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to user, method: :delete, data: { confirm: "Do you really want to delete this user?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(user.updated_at) %> ago
  </div>
</div>

app/views/users/_form.html.erb
<% was_validated = user.errors.any? %>

<%= form_with(model: user, local: true, novalidate: true, class: "mb-3") do |f| %>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/users/_list_item.html.erb
<%= link_to user, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= user %>
    <small class="text-muted">
      <%= time_ago_in_words(user.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/users/_user_dog_owner_profiles.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Dog Owner Profiles

    <a data-toggle="collapse" href="#user_dog_owner_profiles_new_form">
      Add dog owner profile
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @user.dog_owner_profiles.each do |dog_owner_profile| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to dog_owner_profile, dog_owner_profile %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="user_dog_owner_profiles_new_form">
        <%= render partial: "users/user_dog_owner_profiles_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/users/_user_dog_owner_profiles_new_form.html.erb
<%= form_with(model: @dog_owner_profile, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :first_name %>

    <%= f.text_field :first_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :last_name %>

    <%= f.text_field :last_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :phone %>

    <%= f.text_field :phone, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :home_address %>

    <%= f.text_field :home_address, class: "form-control" %>
  </div>

  <%= f.hidden_field :user_id, value: @user.id %>

  <div class="form-group">
    <%= f.label :email %>

    <%= f.text_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :authorized_associates_id %>

    <%= f.text_field :authorized_associates_id, class: "form-control" %>
  </div>

  <%= f.submit "Create dog owner profile", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/users/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit User #<%= @user.id %>
      </h2>

      <div class="card-body">
        <%= render "form", user: @user %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Users

      <%= link_to new_user_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>






<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Users

        <%= link_to new_user_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @users, partial: "list_item", as: :user %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @users, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New User
      </h2>

      <div class="card-body">
        <%= render "form", user: @user %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @user, partial: "card", as: :user %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "users/user_dog_owner_profiles" %>
  </div>
</div>