config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :authorized_associates

      resources :saved_appointments

      resources :services

      resources :dog_profiles

      resources :dog_owner_profiles

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "dog_owner_profiles#index"
  resources :authorized_associates
  resources :saved_appointments
  resources :services
  resources :dog_profiles
  resources :dog_owner_profiles
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/dog_profile.rb
class DogProfile < ApplicationRecord
  # Direct associations

  has_many   :saved_appointments,
             foreign_key: "dog_id",
             dependent: :destroy

  belongs_to :owner,
             class_name: "DogOwnerProfile"

  # Indirect associations

  has_one    :authorized_associate,
             through: :owner,
             source: :authorized_associates

  # Validations

  # Scopes

  def to_s
    dog_name
  end
end

app/controllers/api/v1/dog_profiles_controller.rb
class Api::V1::DogProfilesController < Api::V1::GraphitiController
  def index
    dog_profiles = DogProfileResource.all(params)
    respond_with(dog_profiles)
  end

  def show
    dog_profile = DogProfileResource.find(params)
    respond_with(dog_profile)
  end

  def create
    dog_profile = DogProfileResource.build(params)

    if dog_profile.save
      render jsonapi: dog_profile, status: :created
    else
      render jsonapi_errors: dog_profile
    end
  end

  def update
    dog_profile = DogProfileResource.find(params)

    if dog_profile.update_attributes
      render jsonapi: dog_profile
    else
      render jsonapi_errors: dog_profile
    end
  end

  def destroy
    dog_profile = DogProfileResource.find(params)

    if dog_profile.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: dog_profile
    end
  end
end

app/controllers/dog_profiles_controller.rb
class DogProfilesController < ApplicationController
  before_action :set_dog_profile, only: %i[show edit update destroy]

  def index
    @q = DogProfile.ransack(params[:q])
    @dog_profiles = @q.result(distinct: true).includes(:owner,
                                                       :saved_appointments, :authorized_associate).page(params[:page]).per(10)
  end

  def show
    @saved_appointment = SavedAppointment.new
  end

  def new
    @dog_profile = DogProfile.new
  end

  def edit; end

  def create
    @dog_profile = DogProfile.new(dog_profile_params)

    if @dog_profile.save
      message = "DogProfile was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @dog_profile, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @dog_profile.update(dog_profile_params)
      redirect_to @dog_profile, notice: "Dog profile was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @dog_profile.destroy
    message = "DogProfile was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to dog_profiles_url, notice: message
    end
  end

  private

  def set_dog_profile
    @dog_profile = DogProfile.find(params[:id])
  end

  def dog_profile_params
    params.require(:dog_profile).permit(:dog_name, :owner_id, :breed,
                                        :date_of_birth, :allergies, :behavior_notes, :treats)
  end
end

app/views/dog_profiles/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Dog Profile #<%= dog_profile.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Dog name</dt>
      <dd><%= dog_profile.dog_name %></dd>

      <dt>Owner</dt>
      <dd>
        <% if @dog_profile.owner.present? %>
          <%= link_to dog_profile.owner, dog_profile.owner %>
        <% end %>
      </dd>

      <dt>Breed</dt>
      <dd><%= dog_profile.breed %></dd>

      <dt>Date of birth</dt>
      <dd><%= dog_profile.date_of_birth %></dd>

      <dt>Allergies</dt>
      <dd><%= dog_profile.allergies %></dd>

      <dt>Behavior notes</dt>
      <dd><%= dog_profile.behavior_notes %></dd>

      <dt>Treats</dt>
      <dd><%= dog_profile.treats %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back dog_profile, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_dog_profile_url(dog_profile), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to dog_profile, method: :delete, data: { confirm: "Do you really want to delete this dog_profile?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(dog_profile.updated_at) %> ago
  </div>
</div>

app/views/dog_profiles/_dog_profile_saved_appointments.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Saved Appointments

    <a data-toggle="collapse" href="#dog_profile_saved_appointments_new_form">
      Add saved appointment
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @dog_profile.saved_appointments.each do |saved_appointment| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to saved_appointment, saved_appointment %>

        <%= link_to saved_appointment, method: :delete, data: { confirm: "Do you really want to delete this saved_appointment" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="dog_profile_saved_appointments_new_form">
        <%= render partial: "dog_profiles/dog_profile_saved_appointments_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/dog_profiles/_dog_profile_saved_appointments_new_form.html.erb
<%= form_with(model: @saved_appointment, local: true) do |f| %>

  <%= f.hidden_field :dog_id, value: @dog_profile.id %>

  <div class="form-group">
    <%= f.label :owner_id %>

    <%= f.collection_select :owner_id, DogOwnerProfile.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :nickname_for_appointment %>

    <%= f.text_field :nickname_for_appointment, class: "form-control" %>
  </div>

  <%= f.submit "Create saved appointment", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/dog_profiles/_dog_profiles_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "dog_profiles_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :dog_name_cont, "Dog name contains" %>
    <%= f.text_field :dog_name_cont, :class => "form-control", :placeholder => "Dog name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :treats_cont, "Treats contains" %>
    <%= f.text_field :treats_cont, :class => "form-control", :placeholder => "Treats contains" %>
  </div>

  <div class="form-group">
    <%= f.label :behavior_notes_cont, "Behavior notes contains" %>
    <%= f.text_field :behavior_notes_cont, :class => "form-control", :placeholder => "Behavior notes contains" %>
  </div>

  <div class="form-group">
    <%= f.label :allergies_cont, "Allergies contains" %>
    <%= f.text_field :allergies_cont, :class => "form-control", :placeholder => "Allergies contains" %>
  </div>

  <div class="form-group">
    <%= f.label :date_of_birth_cont, "Date of birth contains" %>
    <%= f.text_field :date_of_birth_cont, :class => "form-control", :placeholder => "Date of birth contains" %>
  </div>

  <div class="form-group">
    <%= f.label :breed_cont, "Breed contains" %>
    <%= f.text_field :breed_cont, :class => "form-control", :placeholder => "Breed contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :owner_first_name_cont, "Owner first_name contains" %>
    <%= f.text_field :owner_first_name_cont, :class => "form-control", :placeholder => "Owner first_name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :authorized_associate_first_name_cont, "Authorized associate first_name contains" %>
    <%= f.text_field :authorized_associate_first_name_cont, :class => "form-control", :placeholder => "Authorized associate first_name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/dog_profiles" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#dog_profiles_filters">
  Show filters
</a>

app/views/dog_profiles/_form.html.erb
<% was_validated = dog_profile.errors.any? %>

<%= form_with(model: dog_profile, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% dog_name_class = "form-control" %>
    <% dog_name_was_invalid = dog_profile.errors.include?(:dog_name) %>

    <% if was_validated %>
      <% if dog_name_was_invalid %>
        <% dog_name_class << " is-invalid" %>
      <% else %>
        <% dog_name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :dog_name %>
    <%= f.text_field :dog_name, class: dog_name_class, placeholder: "Enter dog name" %>
    <% if dog_name_was_invalid %>
      <% dog_profile.errors.full_messages_for(:dog_name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% owner_class = "form-control" %>
    <% owner_was_invalid = dog_profile.errors.include?(:owner) %>

    <% if was_validated %>
      <% if owner_was_invalid %>
        <% owner_class << " is-invalid" %>
      <% else %>
        <% owner_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :owner_id %>
    <%= f.collection_select :owner_id, DogOwnerProfile.all, :id, :to_s, {}, class: "form-control" %>
    <% if owner_was_invalid %>
      <% dog_profile.errors.full_messages_for(:owner).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% breed_class = "form-control" %>
    <% breed_was_invalid = dog_profile.errors.include?(:breed) %>

    <% if was_validated %>
      <% if breed_was_invalid %>
        <% breed_class << " is-invalid" %>
      <% else %>
        <% breed_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :breed %>
    <%= f.text_field :breed, class: breed_class, placeholder: "Enter breed" %>
    <% if breed_was_invalid %>
      <% dog_profile.errors.full_messages_for(:breed).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% date_of_birth_class = "form-control" %>
    <% date_of_birth_was_invalid = dog_profile.errors.include?(:date_of_birth) %>

    <% if was_validated %>
      <% if date_of_birth_was_invalid %>
        <% date_of_birth_class << " is-invalid" %>
      <% else %>
        <% date_of_birth_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :date_of_birth %>
    <%= f.text_field :date_of_birth, class: date_of_birth_class, placeholder: "Enter date of birth" %>
    <% if date_of_birth_was_invalid %>
      <% dog_profile.errors.full_messages_for(:date_of_birth).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% allergy_class = "form-control" %>
    <% allergy_was_invalid = dog_profile.errors.include?(:allergy) %>

    <% if was_validated %>
      <% if allergy_was_invalid %>
        <% allergy_class << " is-invalid" %>
      <% else %>
        <% allergy_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :allergies %>
    <%= f.text_field :allergies, class: allergy_class, placeholder: "Enter allergy" %>
    <% if allergy_was_invalid %>
      <% dog_profile.errors.full_messages_for(:allergy).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% behavior_note_class = "form-control" %>
    <% behavior_note_was_invalid = dog_profile.errors.include?(:behavior_note) %>

    <% if was_validated %>
      <% if behavior_note_was_invalid %>
        <% behavior_note_class << " is-invalid" %>
      <% else %>
        <% behavior_note_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :behavior_notes %>
    <%= f.text_field :behavior_notes, class: behavior_note_class, placeholder: "Enter behavior note" %>
    <% if behavior_note_was_invalid %>
      <% dog_profile.errors.full_messages_for(:behavior_note).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% treat_class = "form-control" %>
    <% treat_was_invalid = dog_profile.errors.include?(:treat) %>

    <% if was_validated %>
      <% if treat_was_invalid %>
        <% treat_class << " is-invalid" %>
      <% else %>
        <% treat_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :treats %>
    <%= f.text_field :treats, class: treat_class, placeholder: "Enter treat" %>
    <% if treat_was_invalid %>
      <% dog_profile.errors.full_messages_for(:treat).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/dog_profiles/_list_item.html.erb
<%= link_to dog_profile, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= dog_profile %>
    <small class="text-muted">
      <%= time_ago_in_words(dog_profile.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/dog_profiles/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Dog Profile #<%= @dog_profile.id %>
      </h2>

      <div class="card-body">
        <%= render "form", dog_profile: @dog_profile %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/dog_profiles/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Dog Profiles

      <%= link_to new_dog_profile_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "dog_profiles/dog_profiles_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Dog Profiles

        <%= link_to new_dog_profile_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @dog_profiles, partial: "list_item", as: :dog_profile %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @dog_profiles, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/dog_profiles/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Dog Profile
      </h2>

      <div class="card-body">
        <%= render "form", dog_profile: @dog_profile %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/dog_profiles/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @dog_profile, partial: "card", as: :dog_profile %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "dog_profiles/dog_profile_saved_appointments" %>
  </div>
</div>